package inc.funnydog.quickfiles.DB;

import java.text.SimpleDateFormat;
import java.util.Date;

import android.annotation.SuppressLint;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "apkgroups")
public class ApkGroup {
    public static final String ID_COL = "ID";
    // id is generated by the database and set on the object automatically
    @DatabaseField(generatedId = true, columnName = ID_COL)
    public int Id;
    
    @DatabaseField(uniqueIndex=true)
    public String Name;
    
    @DatabaseField
    public String Description;
    
    @DatabaseField
    public Date ModifiedDate;

    public ApkGroup() {
    }
    
    @Override
    public boolean equals(Object o) {
        ApkGroup group = (ApkGroup)o;
        if(group != null) {
            return Id == group.Id;
        }
        
        return false;
    }

    @Override
    public int hashCode() {
        return Id;
    }

    @SuppressLint("SimpleDateFormat")
    @Override
    public String toString() {
        return Name;
    }
}
