package inc.funnydog.quickfiles.DB;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "apkitems")
public class ApkItem {
    
    public static final String ID_COL = "ID2";
    public static final String GROUP_COL = "GROUPID";
    public static final String PACKAGE_COL = "PACKAGENAME";
    
    public ApkItem() {}
    
    // id is generated by the database and set on the object automatically
    @DatabaseField(generatedId = true, columnName = ID_COL)
    public int ApkItemId;
    
    @DatabaseField(columnName = GROUP_COL)
    public int GroupId;
    
    @DatabaseField(uniqueIndex=true,columnName = PACKAGE_COL)
    public String PackageName;
    
    public boolean isDeleted = false;
    
    @Override
    public boolean equals(Object o) {
        ApkItem group = (ApkItem)o;
        if(group != null) {
            return ApkItemId == group.ApkItemId;
        }
        
        return false;
    }

    @Override
    public int hashCode() {
        return ApkItemId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(ApkItemId);
        sb.append(", ").append("PackageName=").append(PackageName);
        
        return sb.toString();
    }
}
