package inc.funnydog.quickfiles.DB;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "bookmarks")
public class BookMark {

    public static final String ID_COL = "ID";
    public static final String NAME_COL = "NAME";
    public static final String PATH_COL = "PATH";
    
    public BookMark() {}
    
    // id is generated by the database and set on the object automatically
    @DatabaseField(generatedId = true, columnName = ID_COL)
    public int Id;
    
    @DatabaseField(columnName = NAME_COL)
    public String BookmarkName;
    
    @DatabaseField(columnName = PATH_COL)
    public String BookmarkPath;
}
